[WIP] レシピページ作成
qin-team-recipe/09-frontend pull request #25
Opened 2023-06-29 12:51 UTC by daiki-kon

## 関連するチケット
Close #9

## やったこと
> このプルリクで何をしたのか？
- RecipeStepコンポーネントの作成

## 動作確認

## その他
> レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

mainブランチにレシピページへリンクするコードがなかったので \
`http://localhost:3000/recipe/1`
の直リンクで確認していただけると🙏

2023-07-11 11:07 UTC, yasuk-0714 commented
hirokiさんが新しいデザインをもとに、修正対応を行い、再度レビューを行う。

2023-07-18 09:01 UTC, kkojimawk requested changes
遅くなりすみません。確認しました。

2023-07-18 12:59 UTC, daiki-kon commented on src/app/recipe/[id]/_components/Tabs.tsx
> +    <nav className="flex [&>a]:flex-1 [&>a]:py-2.5 [&>a]:text-center [&>a]:text-sm">
子の要素にスタイルを当てるための記述です🙏
https://tailwindcss.com/docs/hover-focus-and-other-states#using-arbitrary-variants
https://zenn.dev/ixkaito/articles/advanced-tailwindcss#%E5%AD%90%E8%A6%81%E7%B4%A0%E3%82%92%E4%B8%80%E6%8B%AC%E6%8C%87%E5%AE%9A

実はここで子の要素にスタイルを当てるべきかは少し悩んでいて、
このTabコンポーネントを使用する側でスタイルを当てたほうがわかりやすいのかな
という気はしていました。。。。

予期せぬスタイルが設定されることにも繋がると思うので修正させて頂きます🙇‍♂️

2023-07-21 15:53 UTC, daiki-kon commented on src/app/recipe/[id]/_components/IngredientListItem.tsx
> +export const IngredientListItem = ({ name }: Props) => {
修正しました！

2023-07-21 15:53 UTC, daiki-kon commented on src/app/recipe/[id]/_components/Tabs.tsx
> +export const Tabs = ({ activePath, children }: Props) => {
修正しました！

2023-07-21 15:53 UTC, daiki-kon commented on src/app/recipe/[id]/_components/Tabs.tsx
> +    <nav className="flex [&>a]:flex-1 [&>a]:py-2.5 [&>a]:text-center [&>a]:text-sm">
修正しました！

2023-07-21 15:55 UTC, daiki-kon commented on src/app/recipe/[id]/ingredients/page.tsx
> +export default function Ingredients({ params }: { params: { id: number } }) {
他のpageを見ると、現状のやり方と同じ形で引数の段階で代入しているので
統一という意味だとそのままの方がいいのかと思うのですがいかがでしょう🤔

2023-07-21 15:55 UTC, daiki-kon commented on src/app/recipe/[id]/page.tsx
> +export default function Recipe({ params }: { params: { id: number } }) {
他のpageを見ると、現状のやり方と同じ形で引数の段階で代入しているので
統一という意味だとそのままの方がいいのかと思うのですがいかがでしょう🤔

2023-07-21 15:57 UTC, daiki-kon commented on src/app/recipe/[id]/layout.tsx
> +}) {
他のpage, layoutを見ると、現状のやり方と同じ形で引数の段階で代入しているので
統一という意味だとそのままの方がいいのかと思うのですがいかがでしょう🤔

2023-07-23 15:27 UTC, kkojimawk commented on src/app/recipe/[id]/_components/Tabs.tsx
> +    <nav className="flex [&>a]:flex-1 [&>a]:py-2.5 [&>a]:text-center [&>a]:text-sm">
なるほどです！ありがとうございます。
修正確認しました。

2023-07-23 15:28 UTC, kkojimawk commented on src/app/recipe/[id]/ingredients/page.tsx
> +export default function Ingredients({ params }: { params: { id: number } }) {
了解です！pageとlayoutは一旦こちらの方法で大丈夫です。

2023-07-23 15:28 UTC, kkojimawk commented on src/app/recipe/[id]/layout.tsx
> +}) {
了解です！pageとlayoutは一旦こちらの方法で大丈夫です。

2023-07-23 15:28 UTC, kkojimawk commented on src/app/recipe/[id]/page.tsx
> +export default function Recipe({ params }: { params: { id: number } }) {
了解です！pageとlayoutは一旦こちらの方法で大丈夫です。

2023-07-23 15:28 UTC, kkojimawk commented on src/app/recipe/[id]/_components/Tabs.tsx
> +export const Tabs = ({ activePath, children }: Props) => {
ありがとうございます。

2023-07-23 15:43 UTC, kkojimawk approved these changes

2023-07-24 12:46 UTC, merged